## Data Preprocessing

In [35]:
# import library
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
## Load dataset into a dataframe
df = pd.read_excel("../data/raw/Flipkart-Laptops.xlsx")

## Top five observations
df.head()

,Product Name,ProductID,Product image,Actual price,Discount price,Stars,Rating,Reviews,Description,Link
0,MSI Cyborg 15 Intel Core i5 12th Gen 12450H - ...,COMGZW35W3DSJADN,NaN,89990,54990,3.9,7 Ratings,1 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR5 R...,https://www.flipkart.com/msi-cyborg-15-intel-c...
1,MSI Thin 15 Intel Core i7 12th Gen 12650H - (8...,COMGZW37ZX66DBHF,NaN,83990,67990,NIL,NIL,NIL,Intel Core i7 Processor (12th Gen)8 GB DDR4 RA...,https://www.flipkart.com/msi-thin-15-intel-cor...
2,DELL Inspiron 3520 Intel Core i3 12th Gen 1215...,COMGJ75HJGFDJ6JN,NaN,49240,35660,4.2,"1,805 Ratings",143 Reviews,Intel Core i3 Processor (12th Gen)8 GB DDR4 RA...,https://www.flipkart.com/dell-inspiron-3520-in...
3,Acer One (2024) Intel Core i3 11th Gen 1115G4 ...,COMGPF5CQ7VDWDT4,NaN,43999,26990,4.2,"6,977 Ratings",596 Reviews,Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...,https://www.flipkart.com/acer-one-2024-intel-c...
4,Lenovo V15 AMD Ryzen 3 Quad Core 7320U - (8 GB...,COMGPYKZAWY8UX6C,NaN,59400,27989,4.2,"1,263 Ratings",113 Reviews,AMD Ryzen 3 Quad Core Processor8 GB LPDDR5 RAM...,https://www.flipkart.com/lenovo-v15-amd-ryzen-...

### Remove White-space from Columns Name

In [37]:
## Remove white spaces from both sides of each column
df.columns = df.columns.str.strip()
df.columns

Index(['Product Name', 'ProductID', 'Product image', 'Actual price',
       'Discount price', 'Stars', 'Rating', 'Reviews', 'Description', 'Link'],
      dtype='str')

### Work with Price columns

Let's check, how many NIL values contains by 'Actual price' column

In [38]:
## Check the total no. of NIL values
df['Actual price'].str.contains("NIL").sum()

7

In [39]:
round((df['Actual price'].str.contains("NIL").sum()/len(df['Actual price']))*100, 2)

0.73

**Comments:**

There are 7 NIL values that is less than 1%. So, we can drop those observations.

In [40]:
## Remove the "NIL" values from 'Actual price' column 
df = df[df['Actual price'] != "NIL"]

## Display first 3 observations
df.head(3)

,Product Name,ProductID,Product image,Actual price,Discount price,Stars,Rating,Reviews,Description,Link
0,MSI Cyborg 15 Intel Core i5 12th Gen 12450H - ...,COMGZW35W3DSJADN,NaN,89990,54990,3.9,7 Ratings,1 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR5 R...,https://www.flipkart.com/msi-cyborg-15-intel-c...
1,MSI Thin 15 Intel Core i7 12th Gen 12650H - (8...,COMGZW37ZX66DBHF,NaN,83990,67990,NIL,NIL,NIL,Intel Core i7 Processor (12th Gen)8 GB DDR4 RA...,https://www.flipkart.com/msi-thin-15-intel-cor...
2,DELL Inspiron 3520 Intel Core i3 12th Gen 1215...,COMGJ75HJGFDJ6JN,NaN,49240,35660,4.2,"1,805 Ratings",143 Reviews,Intel Core i3 Processor (12th Gen)8 GB DDR4 RA...,https://www.flipkart.com/dell-inspiron-3520-in...

We know that **Actual Price** column and **Discount Price** columns are Object type. For numerical computation, we need to convert those into float type.

In [41]:
##  Convert "Actual price" and "Discount price" columns datatype object to a float
df[["Actual price", "Discount price"]] = df[["Actual price", "Discount price"]].astype(float)

## Check tha data type
print(df["Actual price"].dtype)

## Check tha data type
print(df["Discount price"].dtype)

float64
float64

In [42]:
# Check the information about the data frame
df.info()

<class 'pandas.DataFrame'>
Index: 953 entries, 0 to 959
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product Name    953 non-null    str
 1   ProductID       953 non-null    str
 2   Product image   0 non-null      float64
 3   Actual price    953 non-null    float64
 4   Discount price  953 non-null    float64
 5   Stars           953 non-null    object
 6   Rating          953 non-null    str
 7   Reviews         953 non-null    str
 8   Description     953 non-null    str
 9   Link            953 non-null    str
dtypes: float64(3), object(1), str(6)
memory usage: 81.9+ KB

### Product Image Column
We previously know that "Product image" column has all nan values. So this column is need not necessary for our analysis. So we can drop it from the dataframe.

In [43]:
# Drop the Product image column
df.drop(columns=["Product image"], inplace=True)

# Display first three observations
df.head(3)

,Product Name,ProductID,Actual price,Discount price,Stars,Rating,Reviews,Description,Link
0,MSI Cyborg 15 Intel Core i5 12th Gen 12450H - ...,COMGZW35W3DSJADN,89990.0,54990.0,3.9,7 Ratings,1 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR5 R...,https://www.flipkart.com/msi-cyborg-15-intel-c...
1,MSI Thin 15 Intel Core i7 12th Gen 12650H - (8...,COMGZW37ZX66DBHF,83990.0,67990.0,NIL,NIL,NIL,Intel Core i7 Processor (12th Gen)8 GB DDR4 RA...,https://www.flipkart.com/msi-thin-15-intel-cor...
2,DELL Inspiron 3520 Intel Core i3 12th Gen 1215...,COMGJ75HJGFDJ6JN,49240.0,35660.0,4.2,"1,805 Ratings",143 Reviews,Intel Core i3 Processor (12th Gen)8 GB DDR4 RA...,https://www.flipkart.com/dell-inspiron-3520-in...

In [44]:
df.info()

<class 'pandas.DataFrame'>
Index: 953 entries, 0 to 959
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product Name    953 non-null    str
 1   ProductID       953 non-null    str
 2   Actual price    953 non-null    float64
 3   Discount price  953 non-null    float64
 4   Stars           953 non-null    object
 5   Rating          953 non-null    str
 6   Reviews         953 non-null    str
 7   Description     953 non-null    str
 8   Link            953 non-null    str
dtypes: float64(2), object(1), str(6)
memory usage: 74.5+ KB

### Save processed dataset

In [45]:
df.to_csv("../data/processed/cleaned_flipcart_laptop_data.csv", index=False)